### ISSUE TITLE
[BUG] Missing error-message running: "tiddlywiki --build"

### ISSUE THREAD

**Issue by pmario** [TiddlyWiki/TiddlyWiki5#8694]
To reproduce

- On the command line run `tiddlywiki --build`
- Which can happen, if you have `tiddlywiki %placeholder% --build`, where `%placeholder%` is undefined

You will get: 

```
PS E:\git\tiddly\tiddlywiki\TiddlyWiki5> tiddlywiki  --build
$:/core/modules/commands/build.js:27
        var buildTargets = $tw.boot.wikiInfo.build;
                                             ^

TypeError: Cannot read properties of null (reading 'build')
    at Command.execute ($:/core/modules/commands/build.js:27:39)
    at Commander.executeNextCommand ($:/core/modules/commander.js:107:14)
    at Commander.execute ($:/core/modules/commander.js:64:7)
    at exports.startup ($:/core/modules/startup/commands.js:34:12)
    at $tw.boot.executeNextStartupTask ($:/boot/boot.js:2620:10)
    at $tw.boot.executeNextStartupTask ($:/boot/boot.js:2618:21)
    at $tw.boot.executeNextStartupTask ($:/boot/boot.js:2618:21)
    at $tw.boot.executeNextStartupTask ($:/boot/boot.js:2618:21)
    at $tw.boot.executeNextStartupTask ($:/boot/boot.js:2618:21)
    at $tw.boot.executeNextStartupTask ($:/boot/boot.js:2618:21)

Node.js v20.18.0
```

**Expected**

There should be an error message, that "path" parameter or however this one is named is missing.

**Comment by Jermolene** [comment]
Thanks @pmario
