### ISSUE TITLE
[MWS] Test fails on Windows

### ISSUE THREAD

**Issue by pmario** [TiddlyWiki/TiddlyWiki5#8718]
Node version 22.10.0
Windows 11
PowerShell 7.4.6

It seems there is a clean up task runnig, which may run into a "race condition". 
I did have a look at the directory and it actually **is empty**

```
Suite error: AttachmentStore
  Message:
    Error: ENOTEMPTY: directory not empty, rmdir 'E:\git\tiddly\tiddlywiki\TiddlyWiki5\editions\test\test-store\files\3d919618de9ad6357fc92525c844f907b73f245e1345322276ada9fd68abbc60'
  Stack:
    undefinedError: ENOTEMPTY: directory not empty, rmdir 'E:\git\tiddly\tiddlywiki\TiddlyWiki5\editions\test\test-store\files\3d919618de9ad6357fc92525c844f907b73f245e1345322276ada9fd68abbc60'
        at Object.rmdirSync (node:fs:1201:11)
        at _rmdirSync (node:internal/fs/rimraf:261:21)
        at rimrafSync (node:internal/fs/rimraf:194:7)
        at node:internal/fs/rimraf:254:9
        at <Jasmine>
        at _rmdirSync (node:internal/fs/rimraf:251:7)
        at rimrafSync (node:internal/fs/rimraf:194:7)
        at Object.rmdirSync (node:fs:1195:14)
        at $:/plugins/tiddlywiki/multiwikiserver/modules/tests/test-attachment.js:67:10
        at <Jasmine>
Pending:

1) Tags Operator tests With all indexers should apply tags ordering in order of creation. TW v5.3.7+
  Temporarily disabled with xit


2) Tags Operator tests With no indexers should apply tags ordering in order of creation. TW v5.3.7+
  Temporarily disabled with xit

1372 specs, 1 failure, 2 pending specs
Finished in 128.446 seconds
Randomized with seed 03343 (jasmine --random=true --seed=03343)
Error: Tests failed with code 1
PS E:\git\tiddly\tiddlywiki\TiddlyWiki5>
```

<details><summary>Full Log PowerShell</summary>

```
PS E:\git\tiddly\tiddlywiki\TiddlyWiki5> npm run test

> tiddlywiki@5.3.6-prerelease test
> npm run build:test-edition && npm run test:multiwikiserver-edition


> tiddlywiki@5.3.6-prerelease build:test-edition
> node ./tiddlywiki.js ./editions/test --verbose --version --build index

Boot log:
  Startup task: load-modules
  Startup task: info after: load-modules before: startup
  Startup task: plugins after: load-modules before: startup
  Startup task: startup after: load-modules
  Startup task: multiwikiserver platforms: node before: story
  Startup task: story after: startup
  Startup task: commands platforms: node after: story
Executing command: version
5.3.6-prerelease
Executing command: build index
Executing command: rendertiddler $:/core/save/all test.html text/plain
Executing command: test
Randomized with seed 03343
Started
................................................................................................................................................................................................................................................................................................................................................................should manage groups correctly
.should manage permissions correctly
.should manage users correctly
.should manage roles correctly
......................................................................................................................................................................................................................................................................................................................................................File ./editions/test/test-store/large-file-0.txt generated with size 10485760 bytes
File ./editions/test/test-store/large-file-1.txt generated with size 10485760 bytes
File ./editions/test/test-store/large-file-2.txt generated with size 10485760 bytes
File ./editions/test/test-store/large-file-3.txt generated with size 10485760 bytes
File ./editions/test/test-store/large-file-4.txt generated with size 10485760 bytes
....File ./editions/test/test-store/large-file-0.txt generated with size 10485760 bytes
File ./editions/test/test-store/large-file-1.txt generated with size 10485760 bytes
File ./editions/test/test-store/large-file-2.txt generated with size 10485760 bytes
File ./editions/test/test-store/large-file-3.txt generated with size 10485760 bytes
File ./editions/test/test-store/large-file-4.txt generated with size 10485760 bytes
.File ./editions/test/test-store/large-file.txt generated with size 10485760 bytes
.(node:7868) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
..........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................should manage permissions correctly
.should manage roles correctly
.should manage groups correctly
.should manage users correctly
.............................*.*................................................


Suite error: AttachmentStore
  Message:
    Error: ENOTEMPTY: directory not empty, rmdir 'E:\git\tiddly\tiddlywiki\TiddlyWiki5\editions\test\test-store\files\3d919618de9ad6357fc92525c844f907b73f245e1345322276ada9fd68abbc60'
  Stack:
    undefinedError: ENOTEMPTY: directory not empty, rmdir 'E:\git\tiddly\tiddlywiki\TiddlyWiki5\editions\test\test-store\files\3d919618de9ad6357fc92525c844f907b73f245e1345322276ada9fd68abbc60'
        at Object.rmdirSync (node:fs:1201:11)
        at _rmdirSync (node:internal/fs/rimraf:261:21)
        at rimrafSync (node:internal/fs/rimraf:194:7)
        at node:internal/fs/rimraf:254:9
        at <Jasmine>
        at _rmdirSync (node:internal/fs/rimraf:251:7)
        at rimrafSync (node:internal/fs/rimraf:194:7)
        at Object.rmdirSync (node:fs:1195:14)
        at $:/plugins/tiddlywiki/multiwikiserver/modules/tests/test-attachment.js:67:10
        at <Jasmine>
Pending:

1) Tags Operator tests With all indexers should apply tags ordering in order of creation. TW v5.3.7+
  Temporarily disabled with xit


2) Tags Operator tests With no indexers should apply tags ordering in order of creation. TW v5.3.7+
  Temporarily disabled with xit

1372 specs, 1 failure, 2 pending specs
Finished in 128.446 seconds
Randomized with seed 03343 (jasmine --random=true --seed=03343)
Error: Tests failed with code 1
```

</details>

**Comment by pmario** [comment]
uups I just saw that this is a duplicate from: https://github.com/TiddlyWiki/TiddlyWiki5/issues/8623

I'll close the old one.

**Comment by pmario** [comment]
@Jermolene -- Can you confirm this issue?

**Comment by Jermolene** [comment]
> @Jermolene -- Can you confirm this issue?

I don't have access to a Windows machine at the moment.
