### ISSUE TITLE
[MWS] Server crash when accessing new user

### ISSUE THREAD

**Issue by pmario** [TiddlyWiki/TiddlyWiki5#8720]
@webplusai 

- I did crate a new user
- As soon as the user is created, the server crashes -> but it creates the user so `http://localhost:8080/admin/users` shows the new user
- If I want to show the user profile, the server crashes

![image](https://github.com/user-attachments/assets/dfa323bf-b384-4ede-8ba5-0c6cb322a832)

There seems to be an initialisation problem with the "user role". `userRole` seems to be undefined.
It seems ADMIN role is ID 1 -- So I think a new users **role should be initialized with 0**

Error log

```
syncer-server-filesystem: Dispatching 'save' task: $:/StoryList
Serving on http://127.0.0.1:8080
(press ctrl-C to exit)
$:/plugins/tiddlywiki/multiwikiserver/routes/handlers/manage-user.js:57
                allRoles.sort(function(a, b){ (a.role_id === userRole.role_id ? -1 : 1) });
                                                                      ^

TypeError: Cannot read properties of undefined (reading 'role_id')
    at $:/plugins/tiddlywiki/multiwikiserver/routes/handlers/manage-user.js:57:57
    at Array.sort (<anonymous>)
    at exports.handler ($:/plugins/tiddlywiki/multiwikiserver/routes/handlers/manage-user.js:57:12)
    at Server.requestHandler ($:/plugins/tiddlywiki/multiwikiserver/mws-server.js:484:9)
    at Server.<anonymous> ($:/plugins/tiddlywiki/multiwikiserver/mws-server.js:551:8)
    at Server.emit (node:events:518:28)
    at parserOnIncoming (node:_http_server:1150:12)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:117:17)

Node.js v22.10.0
```

**Comment by pmario** [comment]
The other problem seems to be, that the PW is saved in plain text. 

![image](https://github.com/user-attachments/assets/92cbdd47-6d4e-4b02-aad7-2205ec151810)

**Comment by pmario** [comment]
@webplusai -- Which editor do you use to edit the source code?

It seems your editor adds a lot of redundant TABs, if there are empty lines. 

![image](https://github.com/user-attachments/assets/807b8a8f-3341-45be-b9a3-f1a66649e4ca)

**Comment by pmario** [comment]
@webplusai -- Did you see this issue?  -- I think it is fixed, but it would be nice to get some feedback here.

**Comment by webplusai** [comment]
@pmario that was fixed already on another PR.
