### ISSUE TITLE
[MWS] Delete an active role, crashes the server

### ISSUE THREAD

**Issue by pmario** [TiddlyWiki/TiddlyWiki5#8776]
**To reproduce:** 

- Create a test-user eg: aaa
- Create a role eg: test-role
- Assign test-role to aaa
- Delete role test-role -> Server crashes

**Error log**

```
syncer-server-filesystem: Dispatching 'save' task: $:/StoryList
Serving on http://127.0.0.1:8080
(press ctrl-C to exit)

$:/plugins/tiddlywiki/multiwikiserver/store/sql-engine.js:87
        return statement.run(params);
                         ^
SqliteError: FOREIGN KEY constraint failed
    at SqlEngine.runStatement ($:/plugins/tiddlywiki/multiwikiserver/store/sql-engine.js:87:19)
    at SqlTiddlerDatabase.deleteRole ($:/plugins/tiddlywiki/multiwikiserver/store/sql-tiddler-database.js:1150:14)
    at exports.handler ($:/plugins/tiddlywiki/multiwikiserver/routes/handlers/delete-role.js:42:22)
    at IncomingMessage.<anonymous> ($:/plugins/tiddlywiki/multiwikiserver/mws-server.js:515:10)
    at IncomingMessage.emit (node:events:518:28)
    at endReadableNT (node:internal/streams/readable:1698:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  code: 'SQLITE_CONSTRAINT_FOREIGNKEY'
}

Node.js v22.10.0
```

**Comment by pmario** [comment]
If the role is not assigned to any user -> Delete works

**Comment by pmario** [comment]
@webplusai 

- It seems the **server crash is fixed.**
- The user "aaa" in my case it reset to role USER -- which seems to be OK. 
- The user Role in the screenshot is empty <- **issue**

![image](https://github.com/user-attachments/assets/bb584528-c3fe-4036-ae76-04f63a669ce4)

**Comment by pmario** [comment]
If the role USER is deleted the server crashes again

```
Serving on http://127.0.0.1:8080
(press ctrl-C to exit)

$:/plugins/tiddlywiki/multiwikiserver/store/sql-engine.js:87
	return statement.run(params);
	                 ^
SqliteError: FOREIGN KEY constraint failed
    at SqlEngine.runStatement ($:/plugins/tiddlywiki/multiwikiserver/store/sql-engine.js:87:19)
    at SqlTiddlerDatabase.deleteRole ($:/plugins/tiddlywiki/multiwikiserver/store/sql-tiddler-database.js:1188:14)
    at exports.handler ($:/plugins/tiddlywiki/multiwikiserver/routes/handlers/delete-role.js:48:22)
    at IncomingMessage.<anonymous> ($:/plugins/tiddlywiki/multiwikiserver/mws-server.js:519:10)
    at IncomingMessage.emit (node:events:519:28)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'SQLITE_CONSTRAINT_FOREIGNKEY'
}

Node.js v20.14.0

```
